### ISSUE TITLE
Import does not work

### ISSUE THREAD

**Issue by mopali** [Qantex/LinkedList#3]
Import does not work 😥

**Comment by Qantex** [comment]
Hello @mopali ,
Which development environment do you use?

- **Eclipse or IntelliJ IDEA**

**Comment by mopali** [comment]
@Qantex I use the Eclipse IDE

**Comment by Qantex** [comment]
@mopali I recommend that you look at these steps on this website.

- **[Website](https://www.360logica.com/blog/how-to-import-a-java-project-into-eclipse-ide/)**

**Comment by mopali** [comment]
**@Qantex Thank you very much!**
The **steps** you recommended did help me! **❤ 👍**
