### ISSUE TITLE
How can I change the variable name?

### ISSUE THREAD

**Issue by GeorgeQuaram** [Qantex/LinkedList#4]

**Comment by Qantex** [comment]
### Hello @GeorgeQuaram ,
**to rename this variable**, you only need to change the **variable** **name**.

---
**Follow these steps to change the variable name**
- **1. Click twice on the variable name `list`**
- **2. After you double-clicked the variable name `list`, the variable list was selected.**
- **3. Now you can give the variable a specific name.**
---
- **Remember to make the same change in the other classes after the variable name is changed.**
---

- **— Example = `myList.writeList();`**

**Comment by GeorgeQuaram** [comment]
### Thank you very much for the answer, that helped my very well. _:)_
**I have a question: Which development environment do you consider the best?**

**Comment by Qantex** [comment]
**It makes me happy that I could help you.** 

- **Unfortunately I can't say which is the best development environment, but I can say that the IntelliJ IDEA development environment is my favorite. :)**

**Do you have further questions? :)**

**Comment by GeorgeQuaram** [comment]
No, thank you for thr answer!!! 
### ^-^
